import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/sections/Footer";
export const metadata = {
  title: "Terms of Service | SEOMETRICHUB",
  description:
    "Read the SEOMETRICHUB Terms of Service governing access to and use of our SEO, AI, and digital marketing tools.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <Navbar />
      <main>
      <section className="mx-auto max-w-4xl px-6 py-16 sm:py-20">
        <div className="mb-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-wider text-orange-600">
            Legal
          </p>

          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Terms of Service
          </h1>

          <p className="mt-4 text-sm text-slate-500">
            Last updated: September 7, 2026
          </p>
        </div>

        <div className="space-y-10 text-base leading-8 text-slate-700">
          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              1. Acceptance of Terms
            </h2>

            <p>
              By accessing or using SEOMETRICHUB, you agree to these Terms of
              Service. If you do not agree with these terms, you should not use
              the platform.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              2. About SEOMETRICHUB
            </h2>

            <p>
              SEOMETRICHUB provides SEO, website analysis, keyword research,
              backlink and link analysis, AI content generation, social media
              content generation, competitor analysis, Google Search Console
              integration, and related digital marketing tools.
            </p>

            <p className="mt-4">
              Features may be added, changed, limited, suspended, or removed as
              the platform develops.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              3. Eligibility and Responsible Use
            </h2>

            <p>
              You are responsible for using SEOMETRICHUB lawfully and in a
              manner that does not harm the platform, other users, third-party
              systems, or websites.
            </p>

            <p className="mt-4">
              You must not use the platform to attempt unauthorized access,
              disrupt services, distribute malicious code, violate third-party
              rights, or perform unlawful activities.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              4. Website Analysis
            </h2>

            <p>
              Some SEOMETRICHUB tools analyze publicly accessible website data,
              including HTML, metadata, headings, images, links, response
              information, and technical SEO signals.
            </p>

            <p className="mt-4">
              You are responsible for ensuring that your use of website
              analysis tools complies with applicable laws, website terms, and
              any rights of third parties.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              5. SEO Reports and Recommendations
            </h2>

            <p>
              SEO scores, recommendations, classifications, and analysis
              generated by SEOMETRICHUB are provided for informational and
              decision-support purposes.
            </p>

            <p className="mt-4">
              SEO results may vary based on search engine updates, website
              changes, competition, external factors, and data availability.
              SEOMETRICHUB does not guarantee rankings, traffic, revenue, leads,
              or other specific business outcomes.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              6. Third-Party Data and APIs
            </h2>

            <p>
              Certain features may depend on third-party services, APIs, data
              providers, hosting providers, AI providers, or Google services.
            </p>

            <p className="mt-4">
              Availability, accuracy, limits, pricing, and performance of those
              services may be controlled by the relevant third party and may
              change without notice.
            </p>

            <p className="mt-4">
              SEOMETRICHUB is not responsible for outages, restrictions,
              changes, suspensions, or inaccuracies originating from
              third-party services.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              7. Google Integrations
            </h2>

            <p>
              If you connect a Google account or Google service, you authorize
              SEOMETRICHUB to access only the permissions you approve for the
              requested feature.
            </p>

            <p className="mt-4">
              You may revoke access through your Google Account settings where
              supported.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              8. AI-Generated Content
            </h2>

            <p>
              AI-generated content may contain errors, omissions, unsuitable
              wording, or inaccurate information. You are responsible for
              reviewing, editing, fact-checking, and approving generated
              content before publication or use.
            </p>

            <p className="mt-4">
              You should not rely on AI-generated output as professional legal,
              medical, financial, tax, or other regulated advice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              9. User Inputs
            </h2>

            <p>
              You are responsible for the information, URLs, prompts, keywords,
              topics, and other content you submit to SEOMETRICHUB.
            </p>

            <p className="mt-4">
              You should not submit passwords, private access credentials,
              confidential authentication tokens, or information that you do
              not have permission to use.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              10. Intellectual Property
            </h2>

            <p>
              The SEOMETRICHUB name, platform design, software, interface,
              branding, original content, and related materials are protected
              by applicable intellectual property laws.
            </p>

            <p className="mt-4">
              These Terms do not grant you ownership of SEOMETRICHUB software,
              trademarks, branding, or proprietary technology.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              11. Service Availability
            </h2>

            <p>
              We aim to provide reliable access to SEOMETRICHUB, but continuous,
              uninterrupted, or error-free availability is not guaranteed.
            </p>

            <p className="mt-4">
              Maintenance, updates, hosting issues, API limitations, security
              events, or other technical factors may temporarily affect
              availability.
            </p>
          </section>

                    <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              12. Plans, Payments, Cancellations and Refunds
            </h2>

            <p>
              SEOMETRICHUB may offer free and paid subscription plans with
              different features, usage limits, prices, and subscription
              periods. The applicable plan details and price will be displayed
              before purchase.
            </p>

            <p className="mt-4">
              Payments for paid plans may be processed through third-party
              payment providers. By completing a purchase, you authorize the
              applicable payment provider to process the transaction according
              to the payment details you provide.
            </p>

            <p className="mt-4">
              Access to paid features is activated after a successful payment
              is confirmed. Your paid access remains available for the
              applicable subscription period, subject to these Terms and any
              usage limits associated with your plan.
            </p>

            <p className="mt-4">
              Unless otherwise stated at the time of purchase, successfully
              completed payments for SEOMETRICHUB digital subscription plans
              are generally non-refundable.
            </p>

            <p className="mt-4">
              If you believe you were charged more than once for the same
              purchase, experienced a verified billing error, or paid
              successfully but did not receive the purchased plan, contact us
              at{" "}
              <a
                href="mailto:support@seometrichub.com"
                className="font-semibold text-orange-600 hover:text-orange-700"
              >
                support@seometrichub.com
              </a>
              . We will review the transaction and, where appropriate, provide
              a correction or refund.
            </p>

            <p className="mt-4">
              Where recurring billing or renewal is offered, cancellation
              prevents future renewals or charges after the applicable
              cancellation takes effect. Cancellation does not automatically
              create a refund for an already completed subscription period.
            </p>

            <p className="mt-4">
              Pricing, plan limits, included features, and subscription terms
              may change over time. Any applicable updated terms will be
              presented as required before a new purchase or renewal.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              13. No Guarantees
            </h2>

            <p>
              SEOMETRICHUB is provided on an &quot;as available&quot; basis.
              To the extent permitted by applicable law, we do not guarantee
              that all information, reports, recommendations, AI output, or
              third-party data will always be complete, current, accurate, or
              suitable for every purpose.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              14. Limitation of Liability
            </h2>

            <p>
              To the extent permitted by applicable law, SEOMETRICHUB and its
              operators will not be liable for indirect, incidental,
              consequential, special, or business losses resulting from use of,
              inability to use, or reliance on the platform.
            </p>

            <p className="mt-4">
              This includes losses arising from search ranking changes, website
              modifications, third-party services, AI-generated content,
              inaccurate data, service interruptions, or business decisions
              based on platform output.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              15. Suspension or Termination
            </h2>

            <p>
              Access may be limited, suspended, or terminated where reasonably
              necessary to protect the platform, enforce these Terms, prevent
              abuse, respond to legal requirements, or maintain security.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              16. Changes to These Terms
            </h2>

            <p>
              We may update these Terms as SEOMETRICHUB evolves or as legal,
              technical, or operational requirements change.
            </p>

            <p className="mt-4">
              Updated Terms will be published on this page with a revised
              &quot;Last updated&quot; date.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-slate-900">
              17. Contact
            </h2>

                        <p>
              If you have questions about these Terms of Service, billing,
              payments, subscriptions, or your SEOMETRICHUB account, please
              contact us at{" "}
              <a
                href="mailto:support@seometrichub.com"
                className="font-semibold text-orange-600 hover:text-orange-700"
              >
                support@seometrichub.com
              </a>
              .
            </p>
          </section>
        </div>
      </section>
      </main>
      <Footer />
    </div>
  );
}